version: '3'

services:
  springboilerplate-membership-admin:
    build: .
    image: springboilerplate-membership-admin:0.4-SNAPSHOT
    ports:
      - '3000:80'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    container_name: springboilerplate-membership-admin
    networks:
      - custom_network

networks:
  custom_network:
    external:
      name: local_network
